```{r}
training_set <- read.csv("training_set.csv")
validation_set <- read.csv("validation_set.csv")
test500_set <- read.csv("test500_set.csv")
test500_full <- read.csv("test500_full.csv")
```


```{r}
library(survival)
library(peperr)

pairs(test500_full[,4:ncol(test500_full)])

training_set$interestRate <- as.numeric(as.character(training_set$interestRate))

interestRatebucket=c(rep(0,nrow(training_set)))

for (i in 1:nrow(training_set)) 
{ if (training_set$interestRate[i]<= 2){interestRatebucket[i]="A"}
 # if (training_set$interestRate[i]<= 4 & training_set$interestRate[i]>2){interestRatebucket[i]="B"}
#  if (training_set$interestRate[i]<= 6 & training_set$interestRate[i]>4){interestRatebucket[i]="D"}
   if (training_set$interestRate[i]>2){interestRatebucket[i]="E"}
  
}


training_set=cbind(training_set,interestRatebucket)    

cox_reg=coxph(Surv(start,stop,isDefault)~1+GrossApproval+hpiState+interestRatebucket,
              data=training_set)

summary(cox_reg)

pred_cox_expected=predict(cox_reg,test500_full,type="expected")
cox_test500_cumulativeLambda = c(rep(0,(length(unique(test500_full$loanNum)))))

loanforecastyears=5

for (i in 1:length(unique(test500_full$loanNum))) {
  end_index=loanforecastyears*i
  start_index=end_index-(loanforecastyears-1)
  cox_test500_cumulativeLambda[i]=sum(pred_cox_expected[start_index:end_index])
  }

#Create a data set showing whether loans actually default within 5 year horizon


default_within_5=matrix(0,nrow=length(unique(test500_full$loanNum)),ncol=2)
default_within_5[,1]=unique(test500_full$loanNum)
x=c("loanNum","isDefault")
colnames(default_within_5)=x

for (i in 1:length(unique(test500_full$loanNum))) {
  
  end_index=loanforecastyears*i
  start_index=end_index-(loanforecastyears-1)
  
for (j in start_index:end_index)
  {
  if(test500_full$isDefault[j]==1) {
    default_within_5[i,2]=1
     }
      }
}

prob_default_cox = 1-exp(-cox_test500_cumulativeLambda)
cox_isDefault5=c(rep(0,length(prob_default_cox)))
cox_isDefault5[prob_default_cox>0.2] <- 1
default_within_5=as.data.frame(default_within_5)

confusion_matrix_cox_regression=table(cox_isDefault5,default_within_5$isDefault)
confusion_matrix_cox_regression

test_error= mean((cox_isDefault5-default_within_5$isDefault)^2)
test_error

pr <- prediction(cox_isDefault5,default_within_5$isDefault)

prf <- performance(pr,measure = "tpr",x.measure = "fpr")
plot(prf)


## COX REGRESSION ON VALIDATION SET


#filtered_validation_set=filter(validation_set,endIndicator==1)

#filtered_validation_set=validation_set

pred_cox_expected_validation=predict(cox_reg,validation_set,type="expected")


cox_testvalidation_cumulativeLambda = c(rep(0,(length(unique(validation_set$loanNum)))))

end_index=c(rep(0,length(unique(validation_set$loanNum))+1))
end_index[1]=1
l=2

for (j in 1:nrow(validation_set)) {
  if (validation_set$endIndicator[j]==1){
    end_index[l]=j
    l=l+1
  }
}
  
  
for (i in 1:length(unique(validation_set$loanNum))) {
  
  cox_testvalidation_cumulativeLambda[i]=sum(pred_cox_expected_validation[end_index[i]:end_index[i+1]])
  
  }

cox_prob_default_validation=1-exp(-cox_testvalidation_cumulativeLambda)
cox_isDefault_validation=c(rep(0,length(unique(validation_set$loanNum))))
cox_isDefault_validation[cox_prob_default_validation>0.5] <- 1
filtered_validation_set=filter(validation_set,endIndicator==1)
confusion_matrix_cox_regression=table(cox_isDefault_validation,filtered_validation_set$isDefault)
confusion_matrix_cox_regression

library(ROCR)
pr <- prediction(cox_isDefault_validation,filtered_validation_set$isDefault)
prf <- performance(pr,measure = "tpr",x.measure = "fpr")
plot(prf)


```

