---
title: "Loss Given Default Model"
author: "Yash Tambawala"
date: "March 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Starting the libraries
library(dplyr)
library(GGally)
library(survival)
library(ROCR)

```


# Data set preparation

Creation of Train, Validation and Test set for Time Series Sampling


```{r}
set.seed(1)

df <- read.csv("SBA_cleaned_data.csv")

df.train.ts <- filter(df,ApprovalFiscalYear <= 2002)
df.valid.ts <- filter(df,ApprovalFiscalYear > 2002 & ApprovalFiscalYear <= 2006)
df.test.ts <- filter(df,ApprovalFiscalYear>2006)
```

# Loss given default model

```{r}
set.seed(1)

# Get Loss given default distribution
df.train.default <- df.train.ts[df.train.ts$isDefault==2,]
df.valid.default <- df.valid.ts[df.valid.ts$isDefault==2,]
# Model for prob of default
glm.fit <- glm((isDefault-1) ~ GrossApproval*TermInMonths+
                 GrossApproval*DeliveryMethod+Naics2digits,data = df.train.ts,family="binomial")
# Inserting the probability of default
df.train.default$probDef <- predict(glm.fit,newdata = df.train.default,type = "response")
df.valid.default$probDef <- predict(glm.fit,newdata = df.valid.default,type = "response")

# Removing isDefault from the default data set
df.train.default <- subset(df.train.default,select = -c(isDefault))
df.valid.default <- subset(df.valid.default,select = -c(isDefault))
# Removing LoanStatus column
df.train.default <- subset(df.train.default,select = -c(LoanStatus))
df.valid.default <- subset(df.valid.default,select = -c(LoanStatus))

model.loss.default <- lm(data = df.train.default,GrossChargeOffAmount~ GrossApproval*TermInMonths+
                           GrossApproval*DeliveryMethod+Naics2digits)

summary(model.loss.default)

df.train.default$predLoss <- predict(model.loss.default,newdata = df.train.default)
df.valid.default$predLoss <- predict(model.loss.default,newdata = df.valid.default)
```

